package com.wgb.utils.dao.oracle;

import com.wgb.utils.entity.oracle.BookRecord;
import com.wgb.utils.entity.oracle.BookRecordExample;
import java.util.List;

import com.wgb.utils.entity.oracle.dto.BookRecordDTO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BookRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    int countByExample(BookRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    int deleteByExample(BookRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    int insert(BookRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    int insertSelective(BookRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    List<BookRecord> selectByExample(BookRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    BookRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookRecord record, @Param("example") BookRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookRecord record, @Param("example") BookRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WGB.BOOKRECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookRecord record);

    /**
     * 通过recordDTO获取书籍信息
     * @param bookRecordDTO
     * @return
     */
    List<BookRecord> getBookRecordByDTO(@Param("bookRecordDTO") BookRecordDTO bookRecordDTO);
}