package com.wgb.utils.entity.oracle;

import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.metadata.BaseRowModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BookRecord  extends BaseRowModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WGB.BOOKRECORD.ID
     *
     * @mbggenerated
     */
    @ExcelProperty(value = {"编号"}, index = 0)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WGB.BOOKRECORD.NAME
     *
     * @mbggenerated
     */
    @ExcelProperty(value = {"书籍名称"}, index = 1)
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WGB.BOOKRECORD.REMARKS
     *
     * @mbggenerated
     */
    @ExcelProperty(value = {"备注信息"}, index = 2)
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WGB.BOOKRECORD.UPDATE_TIME
     *
     * @mbggenerated
     */
    @ExcelProperty(value = {"创建时间"}, index = 3)
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WGB.BOOKRECORD.CREATE_TIME
     *
     * @mbggenerated
     */
    @ExcelProperty(value = {"更新时间"}, index = 4)
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WGB.BOOKRECORD.ID
     *
     * @return the value of WGB.BOOKRECORD.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WGB.BOOKRECORD.ID
     *
     * @param id the value for WGB.BOOKRECORD.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WGB.BOOKRECORD.NAME
     *
     * @return the value of WGB.BOOKRECORD.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WGB.BOOKRECORD.NAME
     *
     * @param name the value for WGB.BOOKRECORD.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WGB.BOOKRECORD.REMARKS
     *
     * @return the value of WGB.BOOKRECORD.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WGB.BOOKRECORD.REMARKS
     *
     * @param remarks the value for WGB.BOOKRECORD.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WGB.BOOKRECORD.UPDATE_TIME
     *
     * @return the value of WGB.BOOKRECORD.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WGB.BOOKRECORD.UPDATE_TIME
     *
     * @param updateTime the value for WGB.BOOKRECORD.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WGB.BOOKRECORD.CREATE_TIME
     *
     * @return the value of WGB.BOOKRECORD.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WGB.BOOKRECORD.CREATE_TIME
     *
     * @param createTime the value for WGB.BOOKRECORD.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "ID:" + id + ",NAME:" + name + ",REMARKS:" + remarks + ",UPDATETIME:" + updateTime + ",CREATETIME:" +  createTime;
    }
}